### ISSUE TITLE
Resource pack constantly reapplying

### ISSUE THREAD

**Issue by GalexY727** [Solar-Tweaks/Solar-Engine#1]
OS: Windows
Tweaks version: 4.2.0 (nice)
Engine version: v2.0
Game version: 1.19.2 (sodium)

I am very unsure how this came to be, I may have used f3+c to initiate a game crash, but I honestly don't remember... 
![java_KIW24gsIXc](https://user-images.githubusercontent.com/65139378/205434551-e1a5718f-8a34-4149-8a57-af33f9857e4b.gif)
I am sorry I can't give you very much information.
The only thing I can think of that could correlate to this is that I was setting up a server that had a server resource pack and when I left it unapplied the pack, which made this screen pop up once, but it was not until I logged back on in another day that I am now unable to use the client because of this constant reloading.
Lunar is up to date as of 12/3/22 👍
Issue persists after removing all files from `.minecraft/resourcepacks`
Sorry again for the lack of information!

**Comment by deceased1** [comment]
same here

**Comment by redefault** [comment]
Fixed! use solar engine 2.0.4.

**Comment by GalexY727** [comment]
Looks about right! Neat!
