### ISSUE TITLE
[suggestion] Remove Lunar Watermarks

### ISSUE THREAD

**Issue by Aktimoose** [Solar-Tweaks/Solar-Engine#6]
**Is your feature request related to a problem? Please describe.**
I don't like constant reminders in-game that I'm using Lunar, I just want to use the client as if it were just a basic modded client.

**Describe the solution you'd like**
Option to remove the Lunar Client logo in the inventory, pause menu, as well as the icon next to Lunar users' names in nametags/tab.

**Describe alternatives you've considered**
I've attempted to load a resource pack that just removes the lunar logo, through assets\lunar\logo, but it didn't do anything as the client loads its assets elsewhere.

**Comment by 770grappenmaker** [comment]
I'm positive there is some file that does the trick, if you use the overlays module then you can basically change any texture loaded through minecraft's texture system, which includes the watermarks
