### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by Aetily** [Solar-Tweaks/Solar-Engine#8]
How to install all this on Solar Tweaks?

**Comment by 25huizengek1** [comment]
Bro this IS what powers Solar Tweaks so you won't have to install this. I would suggest looking at [this](https://github.com/Solar-Tweaks/Solar-Tweaks)

**Comment by 770grappenmaker** [comment]
😄

**Comment by Aetily** [comment]
> 😄pls say me!..

**Comment by 770grappenmaker** [comment]
You don't, if you use solar tweaks you automatically have it

**Comment by Aetily** [comment]
> 

thx!..
